---
name: Batch Docker
description: Build and upload a directory full of docker contexts easily
inputs:
  root-directory:
    description: The root directory that contains each of the image directories
    required: true
  changed-files:
    description: A list of files that have changed since the last workflow run
    required: true
  registry:
    description: The prefix for the Docker registry to push to
    required: true
  deploy:
    description: Set to 'false' to disable deployment
    required: false
    default: 'true'
  image-tags:
    description: JSON list of additional tags that will be added to each of the deployed images in the remote container repository.
    required: false
    default: '[]'
runs:
  using: node12
  main: dist/main.js
