name: 'populate-dagbag'
author: 'Don Kim'
description: 'Repopulate an airflow dagbag'
inputs:
  #service_account_key:
    #description: 'Service Account key for authentication'
    #required: true
  project:
    description: 'Project that contains airflow server'
    required: true
  cluster:
    description: 'Cluster that contains airflow server'
    required: true
  zone:
    description: 'Zone that the airflow server is set in'
    required: true
  namespace:
    description: 'Namespace for airflow server'
    required: true
  pod_label:
    description: 'Pod label'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
